### ISSUE TITLE
Update id_token to match spec

### ISSUE THREAD

**Issue by sqrrrl** [googleapis/signet#11]
Minor fix required to the id_token validation. The audience (aud) may now be either a string or array, validation will need to be updated.

Also worth improving the validation in general to check issued & expiration times.

**Comment by mvastola** [comment]
FYI, I think this is fixed via upgrading to `jwt` version `2.x`.

**Comment by dazuma** [comment]
Closing until we determine there's actually something to do here.

**Comment by dazuma** [comment]
Actually, seems to have been addressed by #139
