### ISSUE TITLE
Breaking change introduced

### ISSUE THREAD

**Issue by randavidovitz** [googleapis/signet#116]
I updated my signet from 0.7 to 0.9 and started getting problems to connect to google adwords with error saying AuthenticationError.OAUTH_TOKEN_INVALID

When reviewing the request, i saw the access token that is used is the original expired one and it's not refreshed.

The issue occurs since, we initialized the signet with the following options
1. :access_token
2. :refresh_token
3,. :issued_at => historical time
4. :expires_in => 3600,
5. :id_token

The old signet code would consider this as expired, while the new one identified this as valid and not expired.

I think the fix should be, to reassign expires_at when setting issued_at / other fields and the expires_at was not preset.

**Comment by TheRoyalTnetennba** [comment]
Is this happening on refresh or initially? Could I get full steps to reproduce?

**Comment by dazuma** [comment]
Signet 0.9.2 has been released with https://github.com/googleapis/signet/pull/112
