### ISSUE TITLE
Getting invalid grant while fetching access token 

### ISSUE THREAD

**Issue by mayank2121** [googleapis/signet#123]
I am using `Signet::Oauth2::Client` to get an access token

```
client = Signet::OAuth2::Client.new(
  authorization_uri: 'https://accounts.google.com/o/oauth2/v2/auth',
  token_credential_uri:  'https://www.googleapis.com/oauth2/v4/token',
  client_id: 'my client id',
  client_secret: 'my client secret',
  grant_type: 'authorization_code',
  code: 'my code',
  redirect_uri: 'my redirect uri'
)

client.fetch_access_token!
```

But I am getting an error when I try to fetch access token
`{"error": "invalid_grant", "error_description": "Bad Request"}`

I am not sure why I'm getting this error. Am I missing something? Please help.

Thanks!
@brainopia  @timburks  @blowmage  @sporkmonger

**Comment by blowmage** [comment]
@mayank2121 Does this answer your question?

**Comment by mayank2121** [comment]
@blowmage Yes, It was the case of invalid token.
Thanks for your reply!

**Comment by EyvAZCeferov** [comment]
### sdsdsdsa### sdsdsd### sdsddsa

**Comment by EyvAZCeferov** [comment]
sdasd

**Comment by kishansolankiOpenxcell** [comment]
Not working bitch

**Comment by wes-kay** [comment]
> @blowmage Yes, It was the case of invalid token.
> Thanks for your reply!

How did you remove the invalid tokens?
