### ISSUE TITLE
In which case, Signet::AuthorizationError will be raised?

### ISSUE THREAD

**Issue by xiaoronglv** [googleapis/signet#164]
https://www.rubydoc.info/github/google/signet/Signet/AuthorizationError

I checked the documentation of error `Signet::AuthorizationError `, but didn't find a precious definition of it.

In which case this error will be raised?

- the refresh token is invalid?
-  Does user reset the password?

**Comment by dazuma** [comment]
The `Signet::AuthorizationError` exception is raised when the attempt to obtain an access token fails with a 400, 401, or 403 error. So any of the above (e.g. refresh token is invalid, credentials have expired or been revoked, etc.) could cause it. If you need more information about the specific error, look at the `message` and `response` fields of the exception.
