### ISSUE TITLE
Support for Faraday 2.0.0

### ISSUE THREAD

**Issue by dentarg** [googleapis/signet#205]
Faraday 2.0.0 was just released: https://github.com/lostisland/faraday/releases/tag/v2.0.0

It would be great to be able to use it with `signet`.

https://github.com/googleapis/signet/blob/411f5448ef45190bf45602cd30a6b3480c50e068/signet.gemspec#L23

**Comment by renchap** [comment]
As an alternative to upgrading to Faraday 2, please consider dropping the dependency on Faraday, as it often results in conflicts with other gems or apps that use Faraday and major version bumps might be hard to manage.

**Comment by oshow** [comment]
I agree with reducing the dependencies. But Faraday 2.0 is an update related to middleware and adapters. signet uses neither faraday middleware nor adapters, so I think signet can loose the Faraday's version to 2.0 without doing anything.
