### ISSUE TITLE
Default value of approval_prompt conflicts with optional prompt parameter

### ISSUE THREAD

**Issue by pauljm** [googleapis/signet#22]
Google OAuth2 now accepts a `prompt` parameter that is mutually exclusive with `approval_prompt`. See http://stackoverflow.com/questions/14384354/force-google-account-chooser.

If `approval_prompt` is not included in the `options` hash passed to `Signet::OAuth2::Client#authorization_uri`, it is set to `:force` by default. If `prompt` has also been set, inclusion of `approval_prompt` results in an invalid auth URL.

Suggest imposing a default of `prompt=consent` if neither `approval_prompt` nor `prompt` is provided.

**Comment by raj-k-jangid** [comment]
Thanks.. Its working for me
