### ISSUE TITLE
Gemspec dependency version conflict with code

### ISSUE THREAD

**Issue by dbackeus** [googleapis/signet#50]
In your gemspec you have specified JWT version ~>1.0 and faraday version ~>0.9.

But inside your oauth 2 client you override the dependencies with incompatible versions.

End result is it's impossible to use the signet gem with Bundler, which will install the gemspeced dependencies and subsequently raise error when trying to initialize the oauth client:

```
/home/runner/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.11/lib/bundler/rubygems_integration.rb:266:in `block in replace_gem': can't activate jwt (~> 0.1.4), already activated jwt-1.2.0. Make sure all dependencies are added to Gemfile. (Gem::LoadError)
    from /home/runner/mynewsdesk/vendor/bundle/ruby/2.1.0/gems/signet-0.4.5/lib/signet/oauth_2/client.rb:25:in `<top (required)>'
```

**Comment by willywg** [comment]
Same error here with Rails 3.2

Gem::LoadError: can't activate jwt (~> 0.1.4), already activated jwt-2.0.0. Make sure all dependencies are added to Gemfile.

**Comment by TheRoyalTnetennba** [comment]
Are either of you still experiencing this issue?
