### ISSUE TITLE
Replace faraday with HTTPI

### ISSUE THREAD

**Issue by seuros** [googleapis/signet#77]
@sqrrrl  
Recently i was updating an application that has the the adsword gem, and i noticed that this gem use a different http wrapper than the rest of google's gem.

Do you think it make sense to replace Faraday with HTTPI  ? i could do it in the coming days.

Also travis is not configured for this project.

**Comment by dazuma** [comment]
Realistically, I don't think this is going to happen. While some of the older Google Ads gems are using HTTPI, the Google Cloud gems have standardized on Faraday. So there isn't a significant consistency benefit to be had by switching. (Additionally, Faraday does seem to be more actively maintained than HTTPI recently.)

Regarding Travis: this repo has dropped Travis and is using Kokoro (an internal Google system) for its CI.
