### ISSUE TITLE
Signet still uses client_id and client_secret parameters instead of Authorization header

### ISSUE THREAD

**Issue by sporkmonger** [googleapis/signet#84]
"Including the client credentials in the request-body using the two parameters is NOT RECOMMENDED and SHOULD be limited to clients unable to directly utilize the HTTP Basic authentication scheme (or other password-based HTTP authentication schemes).  The parameters can only be transmitted in the request-body and MUST NOT be included in the request URI."

Back in draft 7 or so when Signet was originally written, it was the other way around, where `client_id` and `client_secret` were the recommended approach. However nowadays, lots of auth servers don't support these parameters (auth servers MAY support them) and Signet should switch to doing what the final RFC recommends.

**Comment by senid231** [comment]
Dropbox uses basic authorization for fetching access token, so `signet` became unusable

https://www.dropbox.com/developers/documentation/http/documentation#oauth2-authorize
