### ISSUE TITLE
Missing "approval_prompt" in authorization_uri

### ISSUE THREAD

**Issue by rems75** [googleapis/signet#87]
I wrote a Rails app synching with Google Calendar. I'm currently trying to obtain new refresh_tokens from the API as a bug prevented me from saving them in the first place.
I am using approval_prompt: force (or prompt: consent I have tried both), the code is: 
   
    google_client = Signet::OAuth2::Client.new({
         client_id: ENV.fetch('GOOGLE_CLIENT_ID'),
         client_secret: ENV.fetch('GOOGLE_CLIENT_SECRET'),
         authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
         scope: Google::Apis::CalendarV3::AUTH_CALENDAR_READONLY,
         redirect_uri: 'http://localhost:8000/google_calendar',
         access_type: "offline",
         approval_prompt: "force"
      })

    URI = google_client.authorization_uri.to_s

The URI does not contain the approval_prompt that I would expect (and when I add it manually, I do get prompted for consent). Am I missing something?

**Comment by TheRoyalTnetennba** [comment]
Sorry for the delayed response. I'm having difficulty reproducing. Is this still giving you issues?
